// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.924
package scheduler

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Layout(title string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<html lang=\"en\" class=\"h-full\"><head><meta charset=\"utf-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1\"><title>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(title)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `views/pages/scheduler/layout.templ`, Line: 8, Col: 17}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, " - BTick Scheduler</title><link rel=\"stylesheet\" href=\"/assets/css/output.css\"><script src=\"/assets/js/lib/htmx.js\"></script></head><body class=\"min-h-full bg-slate-950 text-slate-100 antialiased\"><div class=\"absolute inset-0 -z-10 bg-[radial-gradient(circle_at_15%_20%,rgba(14,165,233,0.20),transparent_35%),radial-gradient(circle_at_85%_10%,rgba(34,197,94,0.18),transparent_32%),linear-gradient(180deg,#020617,#0f172a)]\"></div><header class=\"border-b border-slate-800/80 bg-slate-900/40 backdrop-blur\"><div class=\"mx-auto flex max-w-7xl items-center justify-between px-6 py-4\"><a href=\"/ui/jobs\" class=\"text-xl font-semibold tracking-tight text-cyan-300\">BTick Scheduler</a><nav class=\"flex items-center gap-4 text-sm text-slate-300\"><a class=\"rounded px-2 py-1 hover:bg-slate-800 hover:text-white\" href=\"/ui/jobs\">Jobs</a> <a class=\"rounded px-2 py-1 hover:bg-slate-800 hover:text-white\" href=\"/ui/api-keys\">API Keys</a> <a class=\"rounded px-2 py-1 hover:bg-slate-800 hover:text-white\" href=\"/api/v1/health\">API Health</a></nav></div></header><main class=\"mx-auto w-full max-w-7xl px-6 py-8\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templ_7745c5c3_Var1.Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</main></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
